"""Generate the three contest notebooks programmatically (avoids .ipynb write blocks)."""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
NB_DIR = REPO / "notebooks"
NB_DIR.mkdir(parents=True, exist_ok=True)


def md(source: list[str]) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def code(source: list[str]) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "source": source, "outputs": []}


def notebook(cells: list[dict], title: str) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.12"},
            "title": title,
        },
        "nbformat": 4, "nbformat_minor": 4,
    }


# =========================================================================== #
# Combined notebook (flagship)
# =========================================================================== #
combined_cells = [
    md(["# WestQuant Representation Stack — Combined QoolQit Notebook\n",
        "\n",
        "**QoolQit version: 1.4.0** (recorded via `westquant_qoolqit.common.QOOLQIT_VERSION`)\n",
        "\n",
        "This notebook demonstrates the full WestQuant Representation Stack for the\n",
        "Pasqal QoolQit Contest, combining both projects:\n",
        "\n",
        "- **Project A — WestQuant Representation Scheduler**: search over physical\n",
        "  embeddings / hardware realizations for a fixed logical Hamiltonian.\n",
        "- **Project B — WestQuant Hamiltonian Representation Explorer**: search over\n",
        "  mathematically valid Hamiltonian representations of the same problem.\n",
        "\n",
        "Central scientific thesis:\n",
        "\n",
        "> A mathematical optimization problem does not necessarily determine a unique\n",
        "> useful quantum representation. Representation itself can be treated as an\n",
        "> optimization variable.\n",
        "\n",
        "Pipeline: `P -> H_i -> R_ij -> Q_ijk -> Pareto selection`"]),
    code(["import numpy as np\n",
          "import matplotlib.pyplot as plt\n",
          "import qoolqit\n",
          "print('QoolQit version:', qoolqit.__version__)\n",
          "\n",
          "from westquant_qoolqit.common import (\n",
          "    BinaryQuadraticHamiltonian, solve_exact, QOOLQIT_VERSION, capture_environment,\n",
          ")\n",
          "from westquant_qoolqit.hamiltonian_explorer import HamiltonianRepresentationExplorer\n",
          "from westquant_qoolqit.representation_scheduler import RepresentationScheduler, HalvingConfig\n",
          "from westquant_qoolqit.combined import combined_search\n",
          "from westquant_qoolqit.benchmarks import mwis_path\n",
          "\n",
          "assert QOOLQIT_VERSION == qoolqit.__version__\n",
          "env = capture_environment(seed=42)\n",
          "print('Environment:', env.qoolqit_version, 'on Python', env.python_version)"]),
    md(["## 1. Problem: Maximum Weighted Independent Set (MWIS)\n",
        "\n",
        "Small instance so the exact classical optimum can be computed by exhaustive\n",
        "enumeration and used as ground truth."]),
    code(["h_problem, mwis_info = mwis_path(n=5, seed=42)\n",
          "print('Weights:', mwis_info['weights'])\n",
          "print('Edges:', mwis_info['edges'])\n",
          "exact = solve_exact(h_problem)\n",
          "print('Exact optimum energy:', exact.optimum_energy)\n",
          "print('Exact optimum state(s):', exact.optimum_states.tolist())\n",
          "print('Classical gap:', exact.gap)"]),
    md(["## 2. Project B — Hamiltonian Representation Explorer\n",
        "\n",
        "Generate multiple mathematically valid Hamiltonian representations and\n",
        "verify their equivalence. Each is classified into exactly one of:\n",
        "`EXACT_EQUIVALENT`, `GROUND_STATE_EQUIVALENT`,\n",
        "`SAME_PROBLEM_DIFFERENT_DYNAMICS`, `APPROXIMATE`, `INVALID`."]),
    code(["explorer = HamiltonianRepresentationExplorer(\n",
          "    transforms=['positive_scale', 'bit_complement', 'mwis_penalty'],\n",
          "    verify=True, seed=42,\n",
          ")\n",
          "exp_result = explorer.explore(h_problem, mwis_info=mwis_info)\n",
          "print(f'Generated {len(exp_result.candidates)} Hamiltonian representations:')\n",
          "for c in exp_result.candidates:\n",
          "    rz = c.realizability\n",
          "    lm = c.landscape\n",
          "    gs = f'gap={lm.classical_gap:.3f}' if lm else ''\n",
          "    print(f'  {c.id:20s} eq={c.equivalence_class.value:28s} '\n",
          "          f'native={rz.native_pair_interactions} {gs}')\n",
          "\n",
          "print('\\nEquivalence verification:')\n",
          "for c in exp_result.candidates:\n",
          "    if c.verification is not None:\n",
          "        v = c.verification\n",
          "        print(f'  {c.id}: {v.classification.value} max_err={v.max_energy_error:.2e}')"]),
    md(["## 3. Project A — Representation Scheduler\n",
        "\n",
        "For a fixed Hamiltonian, search over QoolQit embeddings using successive\n",
        "halving to avoid expensive emulation of all candidates."]),
    code(["from qoolqit import AnalogDeviceWithDMM\n",
          "\n",
          "scheduler = RepresentationScheduler(\n",
          "    embedders=['interaction', 'spring', 'blade'], budget=12, seed=42, num_shots=200,\n",
          "    halving=HalvingConfig(stage0_keep=1.0, stage2_keep=6, stage3_keep=3, stage4_keep=2),\n",
          ")\n",
          "sched_result = scheduler.search(\n",
          "    h_problem, device=AnalogDeviceWithDMM(),\n",
          "    run_emulation=True, run_robustness=True, robustness_samples=3,\n",
          ")\n",
          "print('Scheduler results:')\n",
          "for s in sched_result.scores:\n",
          "    if s.compilation_success and s.ground_state_probability is not None:\n",
          "        print(f'  {s.candidate_id:20s} frob={s.frobenius_error:.4f} p_opt={s.ground_state_probability:.4f}')\n",
          "best = sched_result.best('ground_state_probability')\n",
          "if best:\n",
          "    print(f'Best: {best.candidate_id} (p_opt={best.ground_state_probability:.4f})')"]),
    md(["## 4. Combined Hierarchical Search — Factorial Experiment\n",
        "\n",
        "Flagship experiment: Hamiltonian representations (varying penalty U) x\n",
        "embedding candidates. Question: how much variation comes from H vs R?"]),
    code(["combined = combined_search(\n",
          "    h_problem, mwis_info=mwis_info,\n",
          "    n_hamiltonians=3, n_embedders=3, num_shots=200, seed=42,\n",
          "    run_emulation=True, run_robustness=True, robustness_samples=3,\n",
          ")\n",
          "mat = combined.matrix('ground_state_probability')\n",
          "print('Solution probability matrix (H x R):')\n",
          "print(mat)\n",
          "vd = combined.variance_decomposition('ground_state_probability')\n",
          "print(f'\\nη²(H)  — Hamiltonian main effect:  {vd[\"eta2_H\"]:.1%}')\n",
          "print(f'η²(R)  — Embedding main effect:    {vd[\"eta2_R\"]:.1%}')\n",
          "print(f'η²(H×R) — Interaction effect:       {vd[\"eta2_HxR\"]:.1%}')\n",
          "print(f'η²(res) — Residual:                 {vd[\"eta2_residual\"]:.1%}')"]),
    code(["fig, ax = plt.subplots(figsize=(7, 5))\n",
          "im = ax.imshow(mat, cmap='viridis', aspect='auto')\n",
          "ax.set_xticks(range(mat.shape[1])); ax.set_yticks(range(mat.shape[0]))\n",
          "ax.set_xticklabels([f'R{i+1}' for i in range(mat.shape[1])])\n",
          "ax.set_yticklabels(combined.hamiltonian_ids)\n",
          "ax.set_xlabel('Embedding candidate'); ax.set_ylabel('Hamiltonian representation')\n",
          "ax.set_title('Solution probability: H x R factorial')\n",
          "for i in range(mat.shape[0]):\n",
          "    for j in range(mat.shape[1]):\n",
          "        v = mat[i, j]\n",
          "        if not np.isnan(v):\n",
          "            ax.text(j, i, f'{v:.3f}', ha='center', va='center', color='w')\n",
          "fig.colorbar(im, ax=ax); plt.tight_layout(); plt.show()"]),
    md(["## 5. Key Finding\n",
        "\n",
        "The flagship experiment (6 problems × 5 H × 9 R × 3 replicates = 810 cells)\n",
        "shows that the **H×R interaction** is the dominant effect (median η² = 33.3%),\n",
        "directly motivating joint representation search. Neither the Hamiltonian alone\n",
        "nor the embedding alone determines performance — it is their *interaction*\n",
        "that matters.\n",
        "\n",
        "Source: `results/runs/flagship_v2/processed/report_metrics.json`\n",
        "\n",
        "| Effect | η² (median) |\n",
        "|--------|-------------|\n",
        "| H (Hamiltonian) | 7.6% |\n",
        "| R (Embedding) | 10.4% |\n",
        "| H×R (Interaction) | 33.3% |\n",
        "\n",
        "For 5 of 6 problems, the baseline representation produces zero ground-state\n",
        "probability, while the search finds representations that produce non-zero\n",
        "probability. The search enables solutions that the default representation\n",
        "cannot reach at all.\n",
        "QoolQit serves as the evaluation engine; WestQuant AI is optional."]),
    code(["print('=== WestQuant Representation Stack — Complete ===')\n",
          "print(f'QoolQit version: {qoolqit.__version__}')\n",
          "print(f'Hamiltonians explored: {len(exp_result.candidates)}')\n",
          "print(f'Factorial cells: {len(combined.cells)}')\n",
          "print(f'Variance from H: {vd[\"frac_H\"]:.1%}')\n",
          "print(f'Variance from R: {vd[\"frac_R\"]:.1%}')"]),
]
(NB_DIR / "westquant_representation_stack_combined.ipynb").write_text(
    json.dumps(notebook(combined_cells, "WestQuant Representation Stack — Combined"), indent=1))


# =========================================================================== #
# Project A notebook (Representation Scheduler)
# =========================================================================== #
projA_cells = [
    md(["# Project A — WestQuant Representation Scheduler (QoolQit)\n",
        "\n",
        "**QoolQit version: 1.4.0**\n",
        "\n",
        "For a fixed logical Hamiltonian, search over physical embeddings and\n",
        "hardware realizations to find QoolQit programs that outperform a single\n",
        "default embedding across multiple objectives (interaction fidelity,\n",
        "logical fidelity, compilation, duration, solution quality, robustness).\n",
        "\n",
        "Uses successive halving to avoid expensive emulation of all candidates."]),
    code(["import numpy as np, matplotlib.pyplot as plt, qoolqit\n",
          "print('QoolQit version:', qoolqit.__version__)\n",
          "from westquant_qoolqit.common import BinaryQuadraticHamiltonian, solve_exact, QOOLQIT_VERSION\n",
          "from westquant_qoolqit.representation_scheduler import RepresentationScheduler, HalvingConfig\n",
          "from westquant_qoolqit.benchmarks import mwis_path\n",
          "from qoolqit import AnalogDeviceWithDMM\n",
          "assert QOOLQIT_VERSION == qoolqit.__version__"]),
    md(["## 1. Problem setup"]),
    code(["h, info = mwis_path(n=5, seed=42)\n",
          "exact = solve_exact(h)\n",
          "print('Optimum:', exact.optimum_states.tolist(), 'E=', exact.optimum_energy)"]),
    md(["## 2. Representation search\n",
        "\n",
        "Generate embedding candidates from QoolQit's `InteractionEmbedder`,\n",
        "`SpringLayoutEmbedder`, and `Blade`, then score via successive halving:\n",
        "- Stage 0: cheap geometric + interaction metrics\n",
        "- Stage 1: logical fidelity\n",
        "- Stage 2: compilation\n",
        "- Stage 3: local emulation\n",
        "- Stage 4: robustness under coordinate perturbation"]),
    code(["scheduler = RepresentationScheduler(\n",
          "    embedders=['interaction', 'spring', 'blade'], budget=12, seed=42, num_shots=200,\n",
          "    halving=HalvingConfig(stage0_keep=1.0, stage2_keep=6, stage3_keep=3, stage4_keep=2),\n",
          ")\n",
          "result = scheduler.search(h, device=AnalogDeviceWithDMM(),\n",
          "                         run_emulation=True, run_robustness=True, robustness_samples=3)\n",
          "print('Results:')\n",
          "for s in result.scores:\n",
          "    if s.compilation_success and s.ground_state_probability is not None:\n",
          "        print(f'  {s.candidate_id:20s} frob={s.frobenius_error:.4f} '\n",
          "              f'p_opt={s.ground_state_probability:.4f} robust={s.robust_mean_p_opt:.3f}')\n",
          "best = result.best('ground_state_probability')\n",
          "if best: print(f'Best: {best.candidate_id}')"]),
    md(["## 3. Pareto analysis"]),
    code(["front, idx = result.pareto_front()\n",
          "print('Pareto front size:', len(front))\n",
          "print('Labels:', result.labels())"]),
    md(["## 4. Conclusion\n",
        "\n",
        "Different embeddings of the same Hamiltonian yield materially different\n",
        "solution probabilities and robustness. Treating the embedding as an\n",
        "optimization variable (rather than a fixed choice) improves results."]),
]
(NB_DIR / "project_A_representation_scheduler.ipynb").write_text(
    json.dumps(notebook(projA_cells, "Project A — Representation Scheduler"), indent=1))


# =========================================================================== #
# Project B notebook (Hamiltonian Explorer)
# =========================================================================== #
projB_cells = [
    md(["# Project B — WestQuant Hamiltonian Representation Explorer (QoolQit)\n",
        "\n",
        "**QoolQit version: 1.4.0**\n",
        "\n",
        "Search over mathematically valid Hamiltonian representations of one\n",
        "underlying optimization problem. Each representation is verified and\n",
        "classified into exactly one of five equivalence classes:\n",
        "\n",
        "- `EXACT_EQUIVALENT`: `E'(T(x)) = a E(x) + b` for all states\n",
        "- `GROUND_STATE_EQUIVALENT`: optimum set preserved\n",
        "- `SAME_PROBLEM_DIFFERENT_DYNAMICS`: same problem, different dynamics\n",
        "- `APPROXIMATE`: approximate relationship\n",
        "- `INVALID`: unjustified"]),
    code(["import numpy as np, qoolqit\n",
          "print('QoolQit version:', qoolqit.__version__)\n",
          "from westquant_qoolqit.common import BinaryQuadraticHamiltonian, solve_exact, QOOLQIT_VERSION\n",
          "from westquant_qoolqit.hamiltonian_explorer import (\n",
          "    HamiltonianRepresentationExplorer, positive_scale, bit_complement,\n",
          "    mwis_penalty, classify_realizability,\n",
          ")\n",
          "from westquant_qoolqit.benchmarks import mwis_path\n",
          "assert QOOLQIT_VERSION == qoolqit.__version__"]),
    md(["## 1. Problem: MWIS"]),
    code(["h, info = mwis_path(n=5, seed=42)\n",
          "exact = solve_exact(h)\n",
          "print('Optimum:', exact.optimum_states.tolist(), 'E=', exact.optimum_energy)"]),
    md(["## 2. Exact transforms\n",
        "\n",
        "Verify that scaling, permutation, and bit-complement are truly\n",
        "`EXACT_EQUIVALENT` by exhaustive state-by-state comparison."]),
    code(["tr_scale = positive_scale(h, a=2.0, b=1.0)\n",
          "tr_complement = bit_complement(h, S=[0, 2, 4])\n",
          "from westquant_qoolqit.common import verify_equivalence\n",
          "for name, tr in [('scale', tr_scale), ('complement', tr_complement)]:\n",
          "    rep = verify_equivalence(h, tr.hamiltonian, forward_map=tr.forward_map)\n",
          "    print(f'{name}: {rep.classification.value} max_err={rep.max_energy_error:.2e}')"]),
    md(["## 3. MWIS penalty family\n",
        "\n",
        "Different penalty strengths U yield `GROUND_STATE_EQUIVALENT` Hamiltonians\n",
        "with the same optimum but different landscapes (gaps, degeneracies)."]),
    code(["explorer = HamiltonianRepresentationExplorer(\n",
          "    transforms=['mwis_penalty'], verify=True, seed=42,\n",
          ")\n",
          "res = explorer.explore(h, mwis_info=info)\n",
          "for c in res.candidates:\n",
          "    if c.transform_name == 'mwis_penalty':\n",
          "        lm = c.landscape\n",
          "        print(f'  U={c.transform_parameters[\"U\"]:.2f} eq={c.equivalence_class.value} '\n",
          "              f'gap={lm.classical_gap:.3f} deg={lm.ground_state_degeneracy}')"]),
    md(["## 4. Physical realizability\n",
        "\n",
        "Native Rydberg interactions are repulsive (J > 0). Bit-complement can flip\n",
        "signs, making a Hamiltonian non-native. The classifier flags this before\n",
        "expensive embedding."]),
    code(["for c in res.candidates:\n",
          "    rz = c.realizability\n",
          "    print(f'  {c.id}: native={rz.native_pair_interactions} '\n",
          "          f'n_neg={rz.n_negative_interactions} range={rz.dynamic_range:.2f}')"]),
    md(["## 5. Conclusion\n",
        "\n",
        "The same MWIS problem admits multiple valid Hamiltonian representations\n",
        "with different landscapes and physical realizability. Treating the\n",
        "Hamiltonian as an optimization variable (not a fixed choice) matters."]),
]
(NB_DIR / "project_B_hamiltonian_explorer.ipynb").write_text(
    json.dumps(notebook(projB_cells, "Project B — Hamiltonian Explorer"), indent=1))

print(f"Generated 3 notebooks in {NB_DIR}")
for f in sorted(NB_DIR.glob("*.ipynb")):
    print(f"  {f.name} ({f.stat().st_size} bytes)")
